#                            ┑(￣▽￣)┍
#              >>>>>>>>>>>>>>>>>>>>>>>>>
#                Fqstalph
#                         Twitter: @fqstalph
#                 Website: laststyle.tk
#               >>>>>>>>>>>>>>>>>>>>>>>>>
ItemName: "§aItem"
Item1-Command: "help"
#
ItemName2: "Item2"
Item2-Command: "help"
#
ItemName3: "Item3"
Item3-Command: "help"

