#                            ┑(￣▽￣)┍
#              >>>>>>>>>>>>>>>>>>>>>>>>>
#                Fqstalph
#                         Twitter: @fqstalph
#                 Website: github.com/Fqstalph
#               >>>>>>>>>>>>>>>>>>>>>>>>>

# Messages
JoinMessage: "§a+ {player}"
QuitMessage: "§c- {player}"

# Items 
ItemName: "§aItem"
Item1-Command: "help"

ItemName2: "Item2"
Item2-Command: "help"

ItemName3: "Item3"
Item3-Command: "help"
